JACoders/OpenJK

CMakeLists.txt
code/qcommon/files.h
code/rd-common/tr_image_jpg.cpp
code/rd-vanilla/CMakeLists.txt
codemp/client/cl_parse.cpp
codemp/rd-common/tr_image_jpg.cpp
codemp/rd-vanilla/CMakeLists.txt
codemp/server/sv_client.cpp
lib/minizip/ioapi.c
lib/minizip/unzip.h

As I mentioned on #604, distributions like Debian don't like using embedded/bundled code copies, so I'm planning to link OpenJK in Debian contrib to the system zlib. It seems better to use headers that correspond exactly to the system zlib, rather than the header that is bundled in OpenJK.
(This also means I can delete the zlib directory entirely in the Debian package, to know for sure that I'm not using the bundled copy and reduce the number of things I have to do a copyright/license audit on...)

Use system zlib headers if we're using system zlib

---

code/game/g_local.h
code/game/g_public.h

__attribute__((noreturn)), the gcc implementation of NORETURN, is fine
on function pointers, but __declspec(noreturn), the MSVC implementation,
is not.
---
See https://github.com/JACoders/OpenJK/commit/4a09de600ce0c1cdc0e03fc134e192077589957c for discussion

avoid NORETURN macro on function pointer

---

code/qcommon/common.cpp
codemp/qcommon/common.cpp
shared/sys/sys_main.cpp
shared/sys/sys_unix.cpp

without this atty mode is always disabled on unix and command history
doesn't work

Shared: fixed terminal mode and signal handlers on unix

---

codemp/CMakeLists.txt
codemp/cgame/CMakeLists.txt
codemp/game/CMakeLists.txt
codemp/ui/CMakeLists.txt

See #643.
This puts it back the way it was before d4cc979: alternatively we could omit the DLLs on Windows, and/or install to both `base/` and `OpenJK/` (for some reason before d4cc979 this was still done for Mac bundles, but not Windows or Linux).

[MP] Install game, cgame, ui DLLs on non-Mac again

---

shared/sdl/sdl_icon.h

It's mechanically derived from the source file (more precisely, exported in GIMP "C source" format).

sdl_icon.h: this has the same copyright and licensing as the source file

---

code/game/g_savegame.cpp
codeJK2/cgame/cg_weapons.cpp
codeJK2/game/g_savegame.cpp
codeJK2/icarus/blockstream.h
codeJK2/icarus/tokenizer.h

After commit 03235915 removed the inclusion of ibize_platform.h, I get compiler errors in codeJK2 on Linux (gcc).
One of the commits here should also fix #651.

fix fallout from removal of ibize_platform.h

---

code/client/cl_keys.cpp
code/qcommon/common.cpp
code/qcommon/cvar.cpp
code/qcommon/stv_version.h
codemp/client/cl_cgameapi.cpp
codemp/client/cl_keys.cpp
codemp/client/cl_uiapi.cpp
codemp/game/NPC_spawn.c
codemp/game/g_client.c
codemp/game/w_force.c
codemp/qcommon/common.cpp
codemp/qcommon/cvar.cpp
codemp/qcommon/game_version.h
codemp/qcommon/vm.cpp
codemp/server/sv_ccmds.cpp
codemp/server/sv_gameapi.cpp

C++11 reserves syntax like X"foo" and "foo"X for future syntax like
L"a wide-char string", so concatenating macros with literals now
requires an intervening space. Fixes most, if not all, of #651.
---
Tested on Linux, so I could potentially have missed some instances of non-C++11-compliant concatenation in code specific to other platforms - compiling with MSVC in C++11 or C++14 mode would probably detect anything that's left.

Use C++11-compliant string concatenation

---

codemp/qcommon/cm_load.cpp

Since servers are in control of entities, a server can customize base maps by editing the entities chunk of the bsp to add/remote items, spawnpoints, etc.
This patch makes it a bit easier - simply put in your usual path (.pk3 or base/maps/...) a file with .entities tagged onto the end of the name (eg. maps/mp/ffa3.bsp.entities), and you can have your custom entities loaded without changing base assets.

Try to load entities from separate file instead of BSP

---

CMakeLists.txt
code/qcommon/q_platform.h
codeJK2/game/CMakeLists.txt
codemp/qcommon/q_platform.h

Until recently, ioquake3 and its derivatives required trivial code changes every time Linux developers get interested in running it on a new CPU, most recently ioquake/ioq3#128 for ARM64 (aka aarch64). For the vast majority of CPUs, the only change is to add ARCH_STRING detection, which must be kept in sync with the architecture from the build system. I fixed this for ioquake3 in ioquake/ioq3#129, and for iortcw in iortcw/iortcw#2; this branch is an OpenJK version of the same change.
The approach I've taken is to use the ${Architecture} from the CMake build system to define ARCH_STRING in ${SharedDefines} on all platforms except Windows and OS X, making it unnecessary to change anything to support new CPUs in most cases. Code changes should now only be needed if the new CPU is relevant to …

Avoid hard-coding a list of Linux architectures

---

CMakeLists.txt

This partially reverts commit 9a34abf46d3b82729440e46f0e171ae5033dc28a.
We no longer use COMPILE_DEFINITION_* since #687 was merged, so it
is no longer necessary to do this.
---
Just some minor cleanup after #687.

Stop setting CMake policy CMP0043 to OLD

---

code/qcommon/files.cpp
codemp/qcommon/files.cpp

FS_FCloseFile has three main logic paths to close different types of
files.  I've added a better documentation comment explaining what it
does.

Add better documentation of FS_FCloseFile.

---

code/ui/ui_main.cpp
codemp/ui/ui_main.c

playerchoices.txt was being read into a fixed-size buffer without a
length check.  Now, we use a dynamic buffer as the destination.

Fix buffer overflow in {SP,MP} ui_main.{c,cpp}.

---

codemp/game/bg_pmove.c

We shouldn't use clampMin or clampMax until they have been set,
at which point setAngles is set to true. Initializing it to true
defeats that.

MP: PM_VehicleViewAngles: fix use of uninitialized variables

---

.travis.yml
tools/travis-build.sh
tools/travis-install.sh

This branch adds the metadata and scripts to build OpenJK for x86_64 Linux (with gcc and clang) and x86 and x86_64 Windows (with the mingw-w64 gcc toolchain), using [Travis-CI](https://travis-ci.org/). x86 Linux is supported but currently disabled, since it takes a few minutes of package installations to get Travis-CI's 3 year old Ubuntu setup into a state where it can produce 32-bit OpenJK binaries, so this build would lag behind the others.
See https://travis-ci.org/smcv/OpenJK for what the build results look like.
It is based on, and requires, my mingw branch (#688) for the mingw-w64 builds. I could disable those and only build for Linux if people really want that, but testing builds for both Windows and Linux seems better. At the moment, any branch in my clone …

add Travis-CI continuous integration glue

---

codemp/server/server.h
codemp/server/sv_ccmds.cpp
codemp/server/sv_init.cpp

helps keep the number of folders in each directory at a reasonable level,
otherwise demos accumulate and it gets way out of hand

make heirarchical date based demo folders

---

codemp/client/cl_cgameapi.cpp
codemp/qcommon/qcommon.h
codemp/qcommon/vm.cpp
codemp/server/sv_gameapi.cpp
shared/sys/sys_public.h

As mentioned in #719, `vmMain` is not a vararg function and should not be treated as one.
This is the easier fix of the issues mentioned in #719, there's still the matter of handling syscalls correctly.

Fixed incorrectly treating vmMain as vararg

---

code/CMakeLists.txt
code/qcommon/qcommon.h
codemp/CMakeLists.txt
codemp/qcommon/qcommon.h
shared/qcommon/safe/files.cpp
shared/qcommon/safe/files.h

C++11 RAII wrappers for `FS_FileList()` and `FS_ReadFile()`: `FS::FileList()` and `FS::ReadFile()` with foreach support. Removed `FS_AutoReadFile`, which allowed for misuse.
I think using C++'s namespaces for C++ features makes sense, hence the names.

Filesystem RAII

---

codemp/client/cl_main.cpp
codemp/qcommon/qcommon.h

Since fd47854, OpenJK sends along a unique ID (`ja_guid`) as part of userinfo to servers, which identifies a player across game sessions and system restarts. It does this by generating a random 2KiB key file (`jakey`) on first run, then sending a hash of that file and the server address when connecting to a server. This is equivalent to [persistent cookies](https://en.wikipedia.org/wiki/HTTP_cookie#Persistent_cookie) on the World Wide Web.
The `ja_guid` tracking can be useful to server owners as they can log and analyse player behaviour over many sessions, even if the player changes their name while playing or before connecting. It can also provide a weak form of correlation to mod authors for logging per-player info such as K/D ratios and combat stats without having to write an accounts …

Offer opt-out for user tracking functionality (ja_guid)

---

code/cgame/FxScheduler.cpp
code/cgame/FxScheduler.h
code/cgame/FxSystem.cpp
code/cgame/FxSystem.h
code/cgame/FxTemplate.cpp
code/client/snd_music.cpp
code/game/genericparser2.cpp
code/game/genericparser2.h
code/qcommon/q_shared.h
shared/openjk.natvis
shared/qcommon/safe/sscanf.h
shared/qcommon/safe/string.cpp
shared/qcommon/safe/string.h

I've greatly simplified & modernized the Generic Parser 2 in SP; this partially extends to the code using it, in particular the FX Parsing, which also got a first simplification pass (but there's still potential for much more).
The parser is used by FX and DMS parsing; at a glance both effects and music seem to work properly with the new system.
In particular this:
* Gets rid of the unused C interface to the parser
* Removes the unused & unfinished write functionality
* Removes the TextPool (to which all parsed strings were copied) in favor of using string views into the contents of the parsed file, thus removing the need for copies altogether (unless you need a string to be null-terminated)
- as part of this a bunch of functions were made to use string views instead of null-terminated …

[SP] generic parser 2 cleanup

---

README.md

Latest builds of OpenJK seem to search for SDL in homebrew installation locations. They actually crash on launch unless SDL is installed via homebrew.

[README] Fix OS X instructions

---

code/cgame/FxPrimitives.cpp
code/game/AI_Interrogator.cpp
codeJK2/cgame/FxPrimitives.cpp
codeJK2/game/AI_Interrogator.cpp
codemp/game/NPC_AI_Interrogator.c
codemp/game/NPC_AI_Jedi.c

- In kejim_base, killing an interrogation drode at the prison would cause an assertion in Q_irand because of an inverted integer range.
- At the beginning of the artus_topside level, a NaN assertion is thrown.
I believe this commit fixes https://github.com/JACoders/OpenJK/issues/448.

Fix 2 (reproducible) assertion errors of Jedi Outcast

---

.travis.yml
code/qcommon/q_shared.h
codeJK2/game/Q3_Interface.cpp
codemp/qcommon/q_math.c
tools/travis-build.sh
tools/travis-install.sh

The master branch [fails to build on travis-ci](https://travis-ci.org/smcv/OpenJK/builds/87619402) because Ubuntu 12.04's compiler does not support `-std=c++11` (#738). This branch switches to travis-ci's new Ubuntu 14.04 infrastructure, and fixes some compiler errors on that platform, resulting in [a successful build again](https://travis-ci.org/smcv/OpenJK/builds/87619298).
See individual commit mesages for more details.

move travis-ci from Ubuntu 12.04 to 14.04, and fix the build

---

shared/sdl/sdl_window.cpp

noticed two things while porting new SDL code to JK2MV:
- if the opengl context can't be generated it still goes through GLimp_SetMode and returns RSERR_OK.
- no option to allow software GL renderers (OSX VM's have no GPU acceleration, only option you have is to use Apple's software renderer, which is what I'm doing)

ogl improvements

---

shared/qcommon/q_platform.h

This should fix the gcc 4.7 build, which was broken by #856.
Tested with gcc 4.7.
BTW, How about enabling CI on PRs for Linux?

Fix byte order utils for gcc < 4.8

---

codemp/game/ai_main.c

Found by Debian's Lintian tool, which (among many other checks) looks for common misspellings in the string tables of binaries.

Fix a typo in Siege mode: attemtping -> attempting

---

codemp/ui/ui_main.c

This avoids an array underflow: if no servers were found, we would
write to foundPlayerServerNames[-1], which is undefined behaviour, but
with a reasonable assumption of the stack layout is likely to result
in a write to foundPlayerServerAddresses[MAX - 1].
---
Underflow found via compiler warnings that are enabled by default in g++ 6.

Use same mechanism to say "no servers found" as to say how many we found

---

codemp/botlib/l_precomp.cpp

value has type long, or equivalently signed long int. In C,
abs(some_long) returns int (to get a long result you would have to use
labs(some_long) due to lack of overloading), but in C++ it returns long.
---
Found by g++ 6 warnings. The fix should be portable (long int -> `%ld` is Standard C and C++).

botlib: print long int correctly

---

codemp/server/sv_challenge.cpp

This function is only called when debugging challenges.
---
g++ 6 warns about unused static functions by default. It does not warn about unused static inline functions, so this could be made inline instead if desired, but I think this is the better fix.

Suppress compiler warning for unused BufferToHexString

---

shared/qcommon/q_platform.h

In addition to enabling inlining for these very simple functions,
this suppresses warnings from gcc 6:
```
…/shared/qcommon/q_platform.h:302:13: warning: 'void CopyShortSwap(void*, const void*)' defined but not used [-Wunused-function]
```
---
The travis-ci tests on my branch demonstrate this building successfully on g++ and clang, but it would be good if someone could try this on MSVC before merging (hopefully the Appveyor builds do that for us automatically).
`static QINLINE` provokes warnings from clang (because `QINLINE` already contains `static` for clang), but that isn't a regression: there's a lot of that already. As a follow-up change, it would be good if the OpenJK maintainers could choose one of these options:
* define `QINLINE` to `inline` or `__inline` (whichever is supported) …

Declare platform-independent byteswapping functions QINLINE

---

code/game/g_savegame.cpp
code/qcommon/ojk_saved_game.cpp
code/qcommon/ojk_saved_game.h
code/qcommon/ojk_saved_game_class_archivers.h
code/qcommon/ojk_saved_game_helper.h
code/qcommon/ojk_saved_game_helper_fwd.h

VS2013 does not support the `constexpr` keyword so it has been removed.

Remove constexpr usage

---

code/game/g_client.cpp
code/game/g_session.cpp
codeJK2/game/g_client.cpp

```
.../code/game/g_client.cpp:760:6: warning: format '%i' expects argument of type 'int*', but argument 26 has type 'qboolean*' [-Wformat=]
```

Avoid compiler warning when sscanf writes qboolean through %i

---

code/game/G_Timer.cpp
code/game/Q3_Interface.cpp
code/game/g_roff.cpp
code/icarus/IcarusImplementation.cpp
codeJK2/game/Q3_Registers.cpp
codeJK2/game/g_roff.cpp

If a user loads a malicious saved game (perhaps posted on a forum or something), we don't want it to overflow or underflow the buffer.

savegames: bounds-check some string lengths to prevent buffer overflow

---

code/client/cl_cin.cpp
codemp/client/cl_cin.cpp

With clang 3.8:
```
.../codemp/client/cl_cin.cpp: In function ‘short unsigned int yuv_to_rgb(long int, long int, long int)’:
.../codemp/client/cl_cin.cpp:591:2: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
if (r<0) r = 0; if (g<0) g = 0; if (b<0) b = 0;
^~
.../codemp/client/cl_cin.cpp:591:18: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
if (r<0) r = 0; if (g<0) g = 0; if (b<0) b = 0;
^~
```

Use conventional formatting to avoid -Wmisleading-indentation

---

codemp/game/NPC_move.c
codemp/game/bg_pmove.c
shared/qcommon/q_platform.h

The portable idiom for type-safe macro-like constructs in C is to use
"static inline" where C99 inline is supported, or "static __inline"
on compilers that implement that keyword as a compiler-specific
extension (at least gcc, clang and MSVC do), falling back to just
"static" as a last resort on terrible compilers from the distant past.
Using "static QINLINE" everywhere means there is no point in defining
QINLINE to "static inline" on clang, so stop doing that; QINLINE now
consistently expands to Standard C/C++ inline, or __inline on MSVC,
or to nothing if we don't know how to inline functions on this
compiler.
This silences warnings about redundant qualifiers (static static inline)
for all the functions that were already inline.
There are a couple of uses of non-static QINLINE in C++ …

Consistently use "static QINLINE" for inline C code

---

code/client/snd_mem.cpp
codemp/client/snd_mem.cpp

The Debian `powerpc`, `mips` and `s390x` builds failed with:
```
.../code/client/snd_mem.cpp: In function 'qboolean S_LoadSound_Actual(sfx_t*)':
.../code/client/snd_mem.cpp:843:54: error: invalid operands of types '__gnu_cxx::__enable_if<true, double>::__type {aka double}' and 'int' to binary 'operator>>'
if (sfx->fVolRange < (abs(sfx->pSoundData[i]) >> 8))
~~~~~~~~~~~~~~~~~~~~~~~~^~~~
.../code/client/snd_mem.cpp:845:50: error: invalid operands of types '__gnu_cxx::__enable_if<true, double>::__type {aka double}' and 'int' to binary 'operator>>'
sfx->fVolRange = abs(sfx->pSoundData[i]) >> 8;
~~~~~~~~~~~~~~~~~~~~~~~~^~~~
```
This appears to be because `sfx->pSoundData[i]` is of type `short`. C++98
only provided `int abs(int)`, `long abs(long)`, `float abs(float)`,
`double abs(double)` and …

snd_mem: fix build failure on big-endian CPUs with C++11 compilers

---

codemp/client/cl_main.cpp

Hello,
I just found that "ri.GL_ExtensionSupported" was not initialized in the multiplayer code, 
causing it to crash during the initialization.
This pull request proposes a fix for this issue.
Best regards,
Jonathan Pastor

Missing initialization of ri.GL_ExtensionSupported

---

code/cgame/cg_local.h
code/cgame/cg_main.cpp
code/cgame/cg_syscalls.cpp
code/game/g_public.h
code/icarus/IcarusImplementation.cpp
code/qcommon/q_shared.h
code/rd-common/tr_public.h
code/ui/ui_public.h
codeJK2/cgame/cg_local.h
codeJK2/cgame/cg_main.cpp
codeJK2/cgame/cg_syscalls.cpp
codeJK2/game/AI_Utils.cpp
codeJK2/game/g_public.h
codemp/cgame/cg_public.h
codemp/cgame/cg_syscalls.c
codemp/game/NPC_AI_Utils.c
codemp/game/g_public.h
codemp/game/g_syscalls.c
codemp/qcommon/q_shared.h
codemp/rd-common/tr_public.h
codemp/ui/ui_public.h
codemp/ui/ui_shared.h
codemp/ui/ui_syscalls.c
shared/qcommon/q_platform.h

Please see individual commits for details.
If any of the individual patches are not desired, the others can be cherry-picked.

Fix some compiler warnings

---

CMakeLists.txt

This allows the test to match to both Clang and AppleClang, which fixes the build on MacOS systems that use the built in Apple clang compiler.

Use ${CMAKE_C_COMPILER_ID}" MATCHES "Clang"

---

code/client/cl_main.cpp

The renderer isn't initialized until the first frame after the restart. The game frame can run before this happens which will try to do some operations with the renderer, causing the process to crash.
Fix this by ensuring renderer is initialised immediately after being shutdown.

[SP] Fix vid_restart crash

---

code/CMakeLists.txt
codemp/CMakeLists.txt

This will make the macOS app bundle completely self-contained (as it should be), i.e. the client will not need to install SDL2 separately.

Add SDL2 to macOS app bundle

---

code/client/snd_dma.cpp
code/client/snd_local.h
codemp/client/snd_dma.cpp
codemp/client/snd_local.h
shared/sdl/sdl_sound.cpp
shared/sdl/sdl_sound.h

And remove `s_sdlSpeed`. This lets the 'Sound Quality' option in the menu work again.

Use s_khz with SDL sound backend

---

codeJK2/cgame/cg_main.cpp
codeJK2/game/g_local.h
codeJK2/game/g_spawn.cpp
scripts/travis/install.sh

The Allocator is meant to be one that is suitable for allocating
std::pair<key, value> instances, not value instances, and the
Standard C++ library provided by gcc 8 asserts that the types match.
The closest valid allocator here would be
std::allocator<std::pair<key, value>>, but that is the default for
this template anyway, so we can just omit it.
Closes: https://github.com/JACoders/OpenJK/issues/985  
Bug-Debian: https://bugs.debian.org/905477  
Signed-off-by: Simon McVittie <smcv@debian.org>

JK2: Remove mismatched allocator from std::map typedefs

---

code/rd-common/mdx_format.h
code/rd-vanilla/tr_ghoul2.cpp
codemp/rd-common/mdx_format.h
codemp/rd-dedicated/tr_ghoul2.cpp
codemp/rd-vanilla/tr_ghoul2.cpp
codemp/rd-vanilla/tr_model.cpp

The compressed bone pool of a Ghoul II animation file (MDXA, .gla) is always
stored at the end of the file. It is unnecessary to iterate through all frames
to determine the number of compressed bones present on big-endian machines.
This change is applied to the vanilla renderers of the single- and multiplayer
code of JK:JA.

Removed superfluous code to determine the number of compressed bones.

---

codemp/server/sv_client.cpp

Fix exploit to reset player by sending wrong serverId
If client sends wrong serverId but is already active in the world
(CS_ACTIVE) don't resend initial gamestate for the map. This isn't a
valid situation. The player should be CS_CONNECTED or CS_PRIMED.
Resending gamestate to an active player will cause them to respawn
without dying or disconnecting. If the player had a CTF flag it gets
lost until the map is changed or restarted.
Reported by Ensiform at:
https://bugzilla.icculus.org/show_bug.cgi?id=6324

[MP] Merge ioquake/ioq3@b61e299

---

code/rd-vanilla/tr_ghoul2.cpp

Modified tr_ghoul2.cpp, Lines: 3579-3603 to addresss enhancment #1005.
Now the code will look to see if any GLM model has a cinematic GLA for the current map-- and not just _humanoid. This is an enhancement for anyone in the future wanting to create cinematics that involve custom animations for creatures having their own skeletons and GLA files not based on _humanoid.

 Ghoul2 SP enhancment addressing Issue #1005

---

code/game/g_roff.cpp

Fixes for issues #1002 and #1003.  Additional ROFF2 Notetrack enhancements-- added support for new Notetrack types:  USE, loop
Supported notetrack types:    effect, sound, USE, loop
General notetrack format:        \<type\> \<argument\> [additionalArguments]
Note: <> denote required argument, [ ] denote optional argument, | denotes argument choices
Examples:
effect notetrack format:        effect <relative_effectfilepath.efx> [originOffset] [rotationOffset]
notetrack = "effect effects/explosion1.efx 0+0+64 0-0-1";
'effect' notes:
(1) the '+' and '-' are delimiters and not positive/negative signs. For example, negative origin offset would be: -10+-20+-10
(2) angles are expected to be from 0 to 360, i.e., no negative angles.
(3) optional additional argument for rotationOffset requires the …

ROFF2 bug fixes

---

code/game/g_roff.cpp

@xycaleth recommended I use VectorClear to zero-out vec3_t variables in the "loop rof absolute" if block.

Improve code readability... use VectorClear to zero-out vec3_t variables

---

Dockerfile
scripts/docker/functions.sh
scripts/docker/healthcheck.sh
scripts/docker/run.sh
scripts/docker/server.cfg

Hello,
This PR adds the possibility to build a Docker image for OpenJK Linux-based dedicated servers. Docker makes it much easier to run any program in an isolated "container" (see [Wikipedia](https://en.wikipedia.org/wiki/Docker_(software))).
The Dockerfile uses [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/) to compile openjkded and jampgame for both i386 and x86_64, leaving the choice of which to run to the user.
The final image provides the following directory tree and files:
/opt/openjk
/opt/openjk/cdpath
/opt/openjk/cdpath/base
/opt/openjk/cdpath/base/server.cfg
/opt/openjk/cdpath/base/jampgamex86_64.so
/opt/openjk/cdpath/base/jampgamei386.so
/opt/openjk/homepath
/opt/openjk/basepath
/opt/openjk/functions.sh
/opt/openjk/run.sh …

Add Docker support for dedicated server

---

code/rd-vanilla/tr_shadows.cpp
codemp/rd-vanilla/tr_shadows.cpp

GL_Cull already handles if the view is a mirror or not. By also handling
it in RB_DoShadowTessEnd it renders the wrong side of the shadow
geometry. This is fixed by simply removing the mirror handling in
RB_DoShadowTessEnd.

Fix stencil shadows in mirrors

---

code/rd-common/tr_types.h
code/rd-vanilla/qgl.h
code/rd-vanilla/tr_init.cpp
code/rd-vanilla/tr_shadows.cpp
codemp/rd-vanilla/qgl.h
codemp/rd-vanilla/tr_init.cpp
codemp/rd-vanilla/tr_local.h
codemp/rd-vanilla/tr_shadows.cpp

When glStencilOpSeparate is available, the renderer tries to render stencil shadows in one draw call instead of two. It's a neat little performance booster.

Draw stencil shadows in one drawcall when possible

---

code/rd-vanilla/qgl.h
code/rd-vanilla/tr_init.cpp
codemp/rd-vanilla/qgl.h
codemp/rd-vanilla/tr_init.cpp

This PR fixes compile issues on macOS - macOS handles OpenGL functions differently from other operating systems. The GL symbols corresponding to the chosen GL version (either legacy GL 2.1, or core GL 4.2) are linked at link time so the respective functions are guaranteed to exist once the code is compiled. Therefore we can simply define `qglStencilOpSeparate` to be `glStencilOpSeparate` and avoid looking up the function.

Fix glStencilOpSeparate usage for macOS

---

codemp/client/snd_mix.cpp

Fixes https://github.com/JACoders/OpenJK/issues/1038
ofst over-reads past the end of the pSoundData buffer. Add a bounds check
similar to S_CheckAmplitude() in codemp/client/snd_dma.cpp.
https://github.com/JACoders/OpenJK/commit/69800e894dff5ea9fcad22c26cc41c9bbf250216

Add bounds check to resolve buffer over-read

---

codemp/cgame/cg_main.c
codemp/game/g_main.c
codemp/qcommon/q_shared.h
codemp/ui/ui_main.c

1. GCC 10 forbids multiple declarations of global variables, Com_Printf and Com_Error throw compiler errors as a result.
2. Fixes #1034

GCC 10 Compliance

---

codemp/qcommon/files.cpp
codemp/qcommon/qcommon.h
codemp/server/server.h
codemp/server/sv_ccmds.cpp
codemp/server/sv_client.cpp
codemp/server/sv_init.cpp
codemp/server/sv_main.cpp
shared/sys/sys_public.h

This is an redesigned server rate limiter for incoming Out Of Bounds (Connectionless) packets.
The purpose of these patches is to mitigate spoofed IP OOB DOS attacks. This is achieved by two changes:
1. Fixing issue with original q3a rate limiter that was causing very high CPU usage when under such attack, up to the point of rendering server unusable.
2. Allowing "whitelisted" players to fully access OOB server protocol when server is under such attack.
There are 3 new cvars:
- `sv_autoWhitelist` – Enable automatically adding connected players to whitelist
- `sv_maxOOBRate` – Max. incoming OOB packet rate per second. 1000 is default, raising it even more would require code changes.
- `sv_maxOOBRateIP` – Max. incoming OOB packet rate per second for a single IP. 1 is default but there is a …

Improved OOB packet rate limiter

---

codemp/server/sv_main.cpp

This was a simple bug where all loopback oob packets were dropped.

Fix rate limiter blocking packets from loopback (fixes #1048)

---

Dockerfile

Fixes an issue with CMake not resolving the correct path, it isn't clear why this isn't working.
Replacing it with an absolute path (via realpath) allows this to compile.

Fixed issue with toolchain not being detected in Docker build

---

CMakeLists.txt

Powerpc and ARM default to unsigned char which causes an immediate crash when starting the game.
On gcc this is prevented by passing -fsigned-char in CFLAGS and CXXFLAGS. This change does the same for clang.

build: pass -fsigned-char on clang

---

code/game/g_active.cpp

Looking at the other checks in this code I think it is safe to assume that this was meant to be 1050.

Fix typo that causes comparison to always evaluate to false.

---

.github/workflows/build.yml

- Action runner environments to their latest versions. (windows-2022, ubuntu-22.04, macos-12) [[1]](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)
- Action runners to their latest versions. (Fixes nodejs12 and other workflow deprecation warnings)
- Manually, targeting any branch from the actions tab of the repository. [[1]](https://i.imgur.com/i9rlGN4.png)
- Automatically on commits, pull-requests and releases to the master branch.
1. Latest Build, triggered on all commits, pull requests and releases to the master branch. This essentially provides the same effect as the nightly OpenJK builds that users may have been previously accustomed to.
2. Manual release, simply create a release, add a version tag …

(CI/CD) Actions workflow overhaul

---

code/game/Q3_Interface.cpp
code/game/Q3_Interface.h
codeJK2/game/Q3_Interface.cpp
codeJK2/game/Q3_Registers.h
codeJK2/game/g_ICARUS.cpp
codeJK2/game/g_icarus.h
codeJK2/game/g_local.h

Cvar_VariableStringBuffer() does not like unallocated buffers with strlen().
Uses a local variable and cache the result in a map<> that is then cleared upon shutdown.

SP: Attempt to fix GetString() calls with cvars in ICARUS

---

codemp/cgame/cg_view.c

Was missing and created a visual break when using cg_fovAspectAdjust 1. Just copied the correction code from CG_CalcFov.

Also aspect correct the fov in skybox portals

---

codemp/botlib/l_script.cpp

@ensiform, @dionrhys , HI my friends!
Take my bug fix to botlib module.
Problem is that it ignores example hexadecimal values `0xB` `0xC` `0xD` `0xE` `0xF`

Fixed bug with read hexadecimal number in codemp/botlib/l_script

---

codemp/qcommon/RoffSystem.cpp
codemp/qcommon/RoffSystem.h

This pull request fixes two multiplayer bugs related to the RoffSystem:
1. The RoffSystem used the wrong time value (engine time rather than module time) since the times were separated in 92e12a9e9b19525c1f589f1f6779e9397b6bfd26. This caused playback to be incorrect after the first mapchange. The same bug was also introduced by jk2mv and has been fixed the same way in https://github.com/mvdevs/jk2mv/commit/11a108ed4c495b0808f9f15f72f1668149cc4b49.
2. The RoffSystem used `long` instead if `int` for the `mVersion` header field, causing 64-bit versions to be unable to parse roff files and playing them back.

Multiplayer RoffSystem Fixes

---

code/rd-vanilla/tr_WorldEffects.cpp
codemp/rd-vanilla/tr_WorldEffects.cpp

This is also more likely a manifestation of inattention of developers.
Affects behavior:
- `CWindZone::mRDuration`
- `CWindZone::mRDeadTime`
- `CWeatherParticleCloud::mRotationChangeTimer`

Fixed bug in Clear() function SIntRange, mMax is never cleared.

---

code/game/g_navigator.cpp

We loop over EntityList, which can contain MAX_GENTITIES values, but mNeighbors can only contain STEER::MAX_NEIGHBORS values.
I encountered the crash on Windows x64 (with a custom build based on 90e8005b0cef3ce3405ad3f0011a204ca78e4c37) by using the following commands:
```
helpusobi 1
npc spawn kyle
npc spawn reborn (~33 times)
```
Here is the complete callstack i got in Debug:
```
jagamex86_64.dll!ratl::vector_base<ratl::storage::value_semantics<gentity_s *,20>>::push_back(gentity_s * const & value) code/Ratl/vector_vs.h line 205
jagamex86_64.dll!STEER::Activate(gentity_s * actor) code/game/g_navigator.cpp line 4165
jagamex86_64.dll!NPC_MoveToGoal(qboolean tryStraight) code/game/NPC_move.cpp line 805
jagamex86_64.dll!Jedi_Hunt() code/game/AI_Jedi.cpp line 1061 …
```

[SP] Crash when filling SteerUser neighbors (out of bounds vector access)

---

codemp/rd-vanilla/tr_init.cpp

...which affects mods not derived from OJK.
`UI_DrawGLInfo` has an array of size 128, which was being filled from a GL extensions string of 129 words and displaying garbage in the UI.
Discovered by @Daggolin
Ref #472

[MP] fix off-by-one in TruncateGLExtensionsString

---

codemp/qcommon/huffman.cpp
codemp/qcommon/msg.cpp
codemp/qcommon/qcommon.h

@zturtleman recently committed a fix to the Huffman coding in ioquake3's netcode (<https://github.com/ioquake/ioq3/commit/d2b1d124d4055c2fcbe5126863487c52fd58cca1>). This has been treated as a security vulnerability and CVE-2017-11721 was assigned (by someone, it isn't clear who requested this): see <https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-11721>. As another descendant of the Quake III Arena engine, OpenJK seems to have the same issue.
I believe the situation is:
* When reading data out of a message, a crafted message can arrange for the engine (client or server or both, I'm not sure) to read beyond the message bounds, potentially causing a crash (denial of service) or disclosure of memory contents. Remotely crashing a client or server is a minor security vulnerability …

CVE-2017-11721: buffer overflow in MSG_ReadBits

---

code/server/sv_init.cpp

On machines that can load levels faster than the hardcoded entity spawning delay, the Icarus sequencer could reference non-existing entities and therefore fail to chain events to progress cutscenes.
This change increases the number of warmup frames by 1 to push the possible client-server connection time to after all relevant entities have been spawned.
Fixes #1150

Fix hanging cutscenes on fast machines

---

.github/workflows/build.yml

Just to speed up builds and reduce quota usage.
Also formatted `build.yml` with `yaml-language-server`.
Job count: 22 -> 14
Artifacts: 11 -> 9
Build time: 15-20m -> 13m (but most of that was waiting (for build agents?))

exclude builds that match debug+portable, and all of WinXP's debug and portable builds

---

Dockerfile

Dockerfile was failing if you tried to build the image because it could not find OpenGL library.
The issue was caused by not excluding Rend2 for CMake Build inside Dockerfile.

Exclude Rend2 from Dockerfile

---

shared/sys/sys_public.h
shared/sys/sys_unix.cpp
shared/sys/sys_win32.cpp

Calling `Sys_Dirname` on `argv[0]` lead to slashes in `argv[0]` getting overwritten on Linux (and potentially other non-Windows platforms), causing some external script to fail sending signals to the right process, because the path changed.
This pull request adjusts `Sys_Dirname` and `Sys_Basename` to work with a copy of the given string instead of the original. This makes the behavior of both functions more consistent between Windows and other platforms.

Unix: Fix argv[0] getting overwritten on launch

---

code/qcommon/cm_patch.h
codemp/client/cl_main.cpp
codemp/qcommon/cm_patch.h

This pull request introduces a new cvar `cl_filterGames` and defaults it to `MBII MBIIOpenBeta`. Servers using an `fs_game` value that's on the list specified in `cl_filterGames` are going to be ignored on the serverlist. The default value seems to cover the majoriy of MBII servers.
Additionally the `MAX_PATCH_PLANES` value got increased from `2048` to `4096`, because some maps (at least for jk2) require a higher limit.

A few small changes (cl_filterGames + MAX_PATCH_PLANES increase)

---

code/client/cl_console.cpp
code/client/cl_keys.cpp
code/client/cl_main.cpp
code/client/cl_scrn.cpp
code/client/client.h
code/client/keys.h
code/qcommon/common.cpp
code/qcommon/qcommon.h
code/rd-common/tr_font.cpp
code/ui/ui_shared.cpp
codemp/client/cl_console.cpp
codemp/client/cl_keys.cpp
codemp/client/cl_main.cpp
codemp/client/cl_scrn.cpp
codemp/client/client.h
codemp/client/keys.h
codemp/qcommon/common.cpp
codemp/rd-common/tr_font.cpp
shared/qcommon/q_string.c
shared/qcommon/q_string.h
shared/sdl/sdl_input.cpp

This pull request aims to slightly improve the console behavior.
1) It replaces the `SDLK_CARET` shift-requirement when trying to open the console in scancode mode (`cl_consoleUseScanCode`) with the cvar check from jk2mv: `cl_consoleShiftRequirement` (prefixed `mv_` instead of `cl_` on jk2mv).
2) It adds a cvar to set the height of the console: `con_height`.

Improve console and font handling

---

codemp/rd-dedicated/tr_init.cpp
codemp/rd-dedicated/tr_local.h
codemp/rd-rend2/tr_bsp.cpp
codemp/rd-rend2/tr_curve.cpp
codemp/rd-rend2/tr_init.cpp
codemp/rd-rend2/tr_local.h
codemp/rd-vanilla/tr_bsp.cpp
codemp/rd-vanilla/tr_curve.cpp
codemp/rd-vanilla/tr_init.cpp
codemp/rd-vanilla/tr_local.h

Seems to work.
Trailing whitespace removal came along for the ride :shrug:

replace PATCH_STITCHING preprocessor define with r_patchStitching cvar

---

code/cgame/cg_view.cpp
codeJK2/cgame/cg_view.cpp
codemp/cgame/cg_view.c

this should defer an overflow of refents occurring that would result in e.g. map models disappearing (light poles on `mp/ffa5`).
localents are a lower priority, we can afford to miss out on some force push/grip effects in these cases.

[Shared] render local entities as late as possible

---

code/rd-vanilla/tr_image.cpp
codemp/rd-vanilla/tr_image.cpp

...even if no images were deleted.

[Shared] Fix endless loop in Z_Malloc due to imageDeleted always being qtrue

---

code/rd-vanilla/tr_ghoul2.cpp

This is annoying and inconsequential. The game will try to make these combinations work anyway.
It also only affects debug builds :shrug:

[SP] ignore numBones assert if we're mixing jk2/jka models

---

.github/workflows/build-deprecated.yml
.github/workflows/build.yml

Treat WinXP builds as deprecated - they are only run every 4 months (or manually). These builds are very slow and do not provide much for anyone.
Introduce the new macos-14 runner for M1 support in its place. These builds are very fast, and likely to see more use.

[Meta] deprecated WinXP builds, introduce macOS-14 runner for M1 builds

---

README.md

Also passes markdownlint now :)
Best to view the rich diff.
Resolves #1135

[Meta] Update readme

---

codemp/ui/ui_main.c

re-enabling this block that turns e.g. `g_weaponDisable 1` --> `g_weaponDisable 524279`
also fix some stray uninitialised warnings.
fixes #1215

[MP] fix g_weaponDisable + g_forcePowerDisable regression when creating listen servers

---

codemp/game/bg_public.h

Alereon pointed out that CS index 26 is used by deathsythe47/base_entranced@e62eda6, so let's try to not stamp over that with our `CS_LEGACY_FIXES`.
Our configstring was only introduced very recently, so we can probably get away with just changing our index now.
base_entranced now also makes use of most of the other free CS indexes:
- 26: base_entranced: `CS_ENHANCEDLOCATIONS` / clash with our `CS_LEGACY_FIXES`
- [...] used by basejka
- 33: base_entranced: `CS_CUSTOMOBITUARIES`
- 34: base_entranced: `CS_CUSTOMVOTES`
- 35: \<free>
- 36: \<free>
- [...] used by basejka
So I chose 36. I don't know if/what other mods might use this.
The next free slot is 1644 (max: 1700). We could also insert our new configstrings after this index, which hopefully no one else has?
It would look like this: …

avoid configstring index clash with base_entranced

---

code/ui/ui_shared.cpp

This fixes #1214, which was introduced in d786f197d1ebb967707f0570c7d5c0f45205c0a5.

[SP] Adjust MenuFontToReal to only try to register fonts once.

---

code/cgame/cg_local.h
code/cgame/cg_main.cpp
code/cgame/cg_weapons.cpp
code/rd-common/tr_font.cpp
code/ui/ui_atoms.cpp
code/ui/ui_local.h
code/ui/ui_shared.cpp
codemp/rd-common/tr_font.cpp

This pull request fixes 2 bugs in SP:
- the datapad showed incorrect fonts for the weapons and force tabs (#1226)
- the r_reloadfonts command made all fonts vanish
Additionally it adjusts `MenuFontToReal` in the ui module to be more flexible in case of menu files that don't actually load the default fonts.

[SP] Font fixes

---

shared/sdl/sdl_window.cpp

Effect of opengl context leak varies depending on video driver. On my linux intel driver it was adding 4 new threads per vid_restart (+ heap space)
On windows + nvidia driver it didn't add new threads but each vid_restart added considerable amount of heap space to the process.
It's possible that the leak did not happen with some older SDL version, I tested with SDL2 2.28.5

Fix opengl context leak on vid_restart

---

code/CMakeLists.txt

glConfig is a global variable visible to tr_{model,init}.cpp and not
visible to cl_main.cpp, which has its own global cls.glconfig. When
RE_BeginRegistration is being called while the video subsystem is
restarting, explicitly memset glConfig to 0. InitOpenGL depends on
glConfig.vidWidth == 0.
In the codemp/ version, Sys_UnloadDll (dlclose) is sufficient to
remove glConfig, which gets reset to 0 later on. In the code/ version,
even after Sys_UnloadDll (dlclose), the old glConfig and vidWidth
remain, so InitOpenGL fails.

Hack to fix singleplayer crashing when toggling fullscreen.

---

code/cgame/FxPrimitives.cpp
code/cgame/FxPrimitives.h
codeJK2/cgame/FxPrimitives.cpp
codeJK2/cgame/FxPrimitives.h
codemp/client/FxPrimitives.cpp
codemp/client/FxPrimitives.h

> properly fixed disappearing line effects if effect starts behind camera
See https://github.com/entdark/jaMME/commit/4dcef105d3a9bb2a7a4223f2e8af429f514e994a

Applied proper fix from jaMME for lines disappearing at certain angles

---

CMakeLists.txt
shared/sdl/sdl_window.cpp

- Force use of internal libpng on macOS, fixes version mismatch problems on current macOS installations
- SDL_Window fix from https://github.com/ec-/Quake3e/pull/295
- Fixes tabbing out of the game, macbook notch mode, and macOS game mode
- Tested, works locally, used
```
sudo xattr -r -d com.apple.quarantine openjk.arm64.app openjk_sp.arm64.app
codesign --force --deep --sign - openjk.arm64.app openjk_sp.arm64.app
```
To quarantine and codesign the app locally and ran as expected in-game.

macOS libpng, SDL_window fixes 

---

code/client/cl_scrn.cpp
code/rd-vanilla/tr_draw.cpp
code/server/sv_savegame.cpp

When redsaurus fixed the save screenshot (in ff210853d582adcf58578cba9ee2917607d49c7c ), they must have missed the double usage of SCR_GetScreenshot. Besides being used for the savegame thumbnails, it's used directly as an argument for DrawStrechRaw. DrawStrechRaw expects a RGBA buffer to draw to the screen. For drawing the level transition screen correctly I also had to flip the image in RE_GetScreenShot, so I also changed the flipping behaviour when saving the savegame.
Fixes: https://github.com/JACoders/OpenJK/issues/1114

[JO] Fix level transition screen

---

code/game/NPC_behavior.cpp

Irand fails when the requested random range is not below QRAND_MAX, which is 2^15 as it is right now. NPC_BSFlee calls irand (via Q_irand) by requesting the random range within [10000, 50000] which is of course below 2^15 and the game crashes.
Below is my stack trace in gdb:
```
4  0x00007ffff784a486 in __assert_fail () from /usr/lib/libc.so.6
5  0x00007fffd18e5b6c in irand (min=10000, max=50000) at /opt/games/git-openjk/shared/qcommon/q_math.c:252
6  0x00007fffd18e5bcc in Q_irand (value1=10000, value2=50000) at /opt/games/git-openjk/shared/qcommon/q_math.c:264
7  0x00007fffd177c34b in NPC_BSFlee () at /opt/games/git-openjk/code/game/NPC_behavior.cpp:1748
8  0x00007fffd1776525 in NPC_RunBehavior (team=2, bState=10) at /opt/games/git-openjk/code/game/NPC.cpp:2055
9  0x00007fffd1776837 in …
```

[NPC behavior] reduce NPC_BSFlee random range

---

shared/sys/sys_unix.cpp

Portable build makes current directory fs_homepath
Apparently it has never been implemented in sys_unix.cpp, only in sys_win32.cpp

Fix portable build on linux/macos

---

.editorconfig

Set default tab width to 4 and other properties for github pages and text editors (see https://editorconfig.org/)

Add .editorconfig - default indentation for text editors and github

---

shared/sdl/sdl_input.cpp

Now in windowed mode desktop cursor is visible and you can move it out of the game window

Fix in_nograb not releasing the mouse cursor

---

code/cgame/cg_view.cpp
codeJK2/cgame/cg_view.cpp

If you set timescale > 1.0 in SP, your mouse sensitivity gets scaled up with it.
It looks like the intention was to slow your mouse sensitivity down when using force speed/rage, so let's cap timescale's influence to < 1.0

[SP] cap the timescale sensitivity scale when timescale > 1.0

---

CMakeLists.txt

[Shared] provide option to use AddressSanitizer

---

code/rd-vanilla/tr_ghoul2.cpp

Quickly ported from https://github.com/mvdevs/jk2mv/commit/ef336f9fcef8ddb9ec5f642166d5d3727ff73bea, https://github.com/mvdevs/jk2mv/commit/3cd7e5313fb7a8ebb5b6cfb2c236987c33298412, https://github.com/mvdevs/jk2mv/commit/14cb6c9cddc6937c9f7ce00123c300086dacf944
Tested in-game, appears to work as expected.

Support JKA models in OpenJO 

---

.github/workflows/build.yml
shared/sys/sys_win32.cpp

Fixes some regressions introduced in #1176
sys_win32.cpp 
- Replace `q_version.h` definition with `game_version.h` instead of removing it entirely (q_version.h contains the cmakeportable definition when it gets generated, removing it was causing portable builds to not be portable on windows)
build.yml
- Revert action change from `marvinpinto/action-automatic-releases` to `softprops/action-gh-release` as the `softprops` action is not intended for rolling releases, and does not generate release notes in the same fashion that would be compatible for such an intention (ie, listing all commits since the previous latest release), the `marvinpinto` action is deprecated and abandoned, but a custom solution using GitHub CLI would probably be the ideal solution.
- Additionally pins …

[Shared] Fix portable build on windows, revert change to "latest" release action

---

code/qcommon/common.cpp

Reorders SP startup init calls to match the order of the MP binary. Fixes the audio distortion during the LucasArts intro video.
Fixes #897

Reorder init to match MP startup

---

codemp/rd-rend2/tr_weather.cpp

See issue https://github.com/JACoders/OpenJK/issues/1189
The game will crash, if a map features weather (e.g. vjun1) and you noclip far enough beneath the map.
This was caused by an out-of-bounds exception caused by chunkIndex sometimes being negative.
The code change ensures the result is always in the range [0, 2] for each axis. This makes sure chunkIndex is always in [0, 8], which is safe for zoneOffsets[9].

rend2 - fixed out-of-bounds crash with weather
